project_id = "votwokvmqroxidvokexh"

[functions.create-razorpay-order]
verify_jwt = true

[functions.verify-razorpay-payment]
verify_jwt = true

[functions.flight-api]
verify_jwt = false

[functions.sms-otp]
verify_jwt = false

[functions.email-otp]
verify_jwt = false
